services:
  - type: web
    name: n8ntest
    env: python
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y wget unzip curl
      apt-get install -y chromium-browser chromium-driver  # ✅ 둘 다 설치
      pip install -r requirements.txt
    startCommand: gunicorn blog_selenium_server:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
